version: "3.8"
services:
  application:
    build: .
    container_name: application-container-partie5
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8086:80"
    networks:
      - network
    links:
      - mysql
  mysql:
    image: mysql
    container_name: mysql-container-partie5
    command: --init-file /data/init.sql --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init.sql:/data/init.sql
    ports:
      - "3306:3306"
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: base
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - "8070:80"
    networks:
      - network
    environment:
      PMA_HOST: mysql
networks:
  network:
    driver: bridge
